---
title: "p8105_hw5_tg2753"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Problem 1
import and clean the data
```{r}
homicide_df =
  read.csv("./homicide-data.csv", na = c("", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolved = case_when(
           disposition =="Closed without arrest" ~ "unsolved",
           disposition =="Open/No arrest" ~"unsolved",
           disposition =="Closed by arrest" ~ "solved"
         )) %>% 
  relocate(city_state)%>%
  filter(city_state != "TulsaAL")
```
focus on Baltimore,MD
```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolved == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n)
)

baltimore_test %>% 
  broom::tidy()
```
iterate across cities
```{r}
prop_test_function = function(city_df){
  
  city_summary = 
    city_df %>%
    summarize(
      unsolved = sum(resolved == "unsolved"),
      n = n()
      )
  
  city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n)
      )
  
  return(city_test)
  
}

prop_test_function(baltimore_df)

homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()
```
iterate across all cities
```{r}
results_df = 
  homicide_df %>% 
  nest(data = uid:resolved) %>% 
  mutate(
    test_results = map(data,prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))

results_df
```
another way of iteration
```{r}
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    unsolved = sum(resolved == "unsolved"),
    n = n()
  ) %>% 
  mutate(
    test_results = map2(unsolved, n, prop.test),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```
make plot
```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2
```{r message=FALSE, warning=FALSE}
df = tibble(path = list.files("./data")) %>% 
    mutate(
    path = str_c("./data/", path),
    data = map(path, read_csv)) %>% 
  unnest(data) %>%
  mutate(
    arm = str_sub(path, start = 8,end = 10),
    subject_id = str_sub(path, start = 12,end = 13)) %>% 
    select(-path)%>%
    pivot_longer(
    week_1:week_8,
    names_to = "n_week",
    values_to = "observation")
df
```
make spaghetti plot
```{r}
df %>% 
  group_by(subject_id) %>% 
  ggplot(aes(x = n_week, y = observation, group = subject_id, color = arm)) +
  geom_point() +
  geom_path() +
  labs(x = "Week",
       y = "Observations",
       title = " Observations On Each Subject Over Time")
```
it is clear that the observation value for experiment arm is larger than the value in control arm on average.

## Problem 3
load the data set
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```
write function
```{r}
fill_in_missing = function(x){
  
  if(is.numeric(x)){
    x = replace(x, is.na(x), mean(x, na.rm = TRUE))
  }
  else if(is.character(x)){
    x = replace(x, is.na(x), "virginica")
  }
  
  return(x)
}
```
fill in missing value with this function
```{r}
result =  map_dfr(iris_with_missing, fill_in_missing)
result
```

